Fix gcc11 build errors
- Include required header file <limits>
- Fixes the following errors when compiling with GCC 11:
  lib/programmemory.cpp:477:44: error: 'numeric_limits' is not a member
  of 'std'
  test/testsymboldatabase.cpp:5978:18: error: 'numeric_limits' is not a
  member of 'std'