Fixes #13956: VisualStudio Importer: Define UNICODE=1;_UNICODE=1 if CharacterSet is Unicode (#7586)
These defines are set by msbuild if CharacterSet is set to Unicode. 


[TestCppCheckProject.zip](https://github.com/user-attachments/files/20694856/TestCppCheckProject.zip)
This test project compiles fine but the current cppcheck version
reports:
```
$ cppcheck --project=TestCppCheckProject.sln --project-configuration="Debug|Win32"
Checking main.cpp Debug|Win32...
main.cpp:7:0: error: #error "nicht definiert" [preprocessorErrorDirective]
#error "nicht definiert"
^
```
with this PR 
```
$ cppcheck --project=TestCppCheckProject.sln --project-configuration="Debug|Win32"...
Checking main.cpp Debug|Win32...
Checking main.cpp: _WIN32=1;WIN32=1;_DEBUG=1;_CONSOLE=1;__SSE2__=1;UNICODE=1;_UNICODE=1;_MSC_VER=1900...
```

<details><summary>main.cpp</summary>
<p>

```cpp
#include <iostream>

#ifndef _UNICODE
#error "nicht definiert"
#endif

#ifndef UNICODE
#error "Not supported"
#endif // UNICODE


int main()
{

        std::cout << "Hello World!\n";
}
```

</p>
</details>