Fix #14423: Add support for Cairo, GLib, GTK and ATK version check macros (#8147)
Without those known to cppcheck, it now bails out with something like
this:

```
test/cfg/gtk.c:16:2: error: failed to evaluate #if condition, undefined function-like macro invocation: GLIB_CHECK_VERSION( ... ) [syntaxError]
#if GLIB_CHECK_VERSION(2, 3, 4)
 ^
```

So define them in a best-effort fashion:
* Cairo is actually using the real value (not that it's likely to
matter)
* GLib, GTK and ATK make them result to `1` as there's no better
alternative than an arbitrary boolean value, and those checks are
usually guarding newer or optional code paths, so it conceptually makes
more sense to have a truthy value.