Fix FP due to namespace scope
```
namespace test {
class Foo {};
struct Bar {
  Foo *_foo;
};

int f(Bar *bar);

void g(Bar *bar) {
  {
    Foo foo;
    bar->_foo = &foo;
    bar->_foo = nullptr;
  }
  f(bar);
}
}
```
would give
```
a.cpp:15:5: error: Using pointer to local variable 'foo' that is out of scope. [invalidLifetime]
  f(bar);
    ^
a.cpp:12:17: note: Address of variable taken here.
    bar->_foo = &foo;
                ^
a.cpp:11:9: note: Variable created here.
    Foo foo;
        ^
```