lib/sourcelocation.h: add missing <cstdint> include
Without the change build on upcoming gcc-13 fails as:

    In file included from lib/symboldatabase.h:28,
                     from lib/astutils.h:36,
                     from test/testastutils.cpp:20:
    lib/sourcelocation.h:52:10: error: 'uint_least32_t' in namespace 'std' does not name a type
       52 |     std::uint_least32_t m_line = 0;
          |          ^~~~~~~~~~~~~~