fix #13854: memleak might show misleading location (#7796)
This sets the column of added braces to the column of the token before
it, so we can point to the last token of the scope.
```
Checking tickets/13854.c ...
tickets/13854.c:3:30: error: Memory leak: p1 [memleak]
        void * p1 = malloc(5);
                             ^
```