test/cfg/boost.cpp: added missing include for `BOOST_SCOPED_ENUM_DECLARE_*` (#6808)
Fixes potential syntax checking in cfg tests on `macos-12` as some
runners might now have Boost installed:
```
Boost found and working, checking syntax with g++ now.
/Users/runner/work/cppcheck/cppcheck/test/cfg/boost.cpp:90:49: error: expected ';' after expression
    BOOST_SCOPED_ENUM_DECLARE_BEGIN(future_errc) {
                                                ^
                                                ;
/Users/runner/work/cppcheck/cppcheck/test/cfg/boost.cpp:90:37: error: use of undeclared identifier 'future_errc'
    BOOST_SCOPED_ENUM_DECLARE_BEGIN(future_errc) {
                                    ^
/Users/runner/work/cppcheck/cppcheck/test/cfg/boost.cpp:92:9: error: use of undeclared identifier 'no_state'
        no_state
        ^
/Users/runner/work/cppcheck/cppcheck/test/cfg/boost.cpp:94:47: error: expected ';' after expression
    BOOST_SCOPED_ENUM_DECLARE_END(future_errc)
                                              ^
                                              ;
/Users/runner/work/cppcheck/cppcheck/test/cfg/boost.cpp:94:35: error: use of undeclared identifier 'future_errc'
    BOOST_SCOPED_ENUM_DECLARE_END(future_errc)
                                  ^
5 errors generated.
make: *** [checkcfg] Error 1
```

(cherry picked from commit 31991023b75ff4e5cc1c6dac39756fc06b8f7ab8)